import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const resources = {
  uk: {
    translation: {
      header: {
        leaveRequest: 'Залишити заявку',
        adminPanel: 'Адмін панель',
        logout: 'Вийти',
      },
      sidebar: {
        home: 'Головна',
        order: 'Авто на замовлення',
        auction: 'Аукціон',
        delivery: 'Доставка',
        contacts: 'Контакти',
        social: 'Соц. мережі',
      },
      footer: {
        branches: 'Наші відділення',
        company: 'Компанія',
        services: 'Послуги',
        socialMedia: 'Ми в соцмережах',
        location: 'Біла Церква',
        address: 'вул. Ярослава Мудрого, 45',
        phone1: '+38 (099) 999 99 99',
        phone2: '+38 (066) 666 66 66',
        copy: '© {{year}} Car Auction. Всі права захищені.',
      },
      footerLinks: {
        about: 'Про нас',
        howWeWork: 'Як ми працюємо',
        delivery: 'Доставка',
        reviews: 'Відгуки',
        contacts: 'Контакти',
        usa: 'Авто з США',
        europe: 'Авто з Європи',
        canada: 'Авто з Канади',
        selection: 'Підбір авто',
        calculator: 'Калькулятор',
      },
      hero: {
        titleLine1: 'Знайди своє авто на',
        titleHighlight: 'Car Auction',
        subtitle1: 'Підбір, перевірка, доставка - все в одному місці.',
        subtitle2:
          'Обирай авто з аукціону або машину під ключ, і ми підберемо найкращий шлях до твого гаражу.',
        orderButton: 'Авто на замовлення',
        auctionButton: 'Перейти до аукціону',
        popularCars: 'Популярні авто',
      },
      carCards: {
        top: 'Топ',
        sales: 'продаж',
      },
      advantages: {
        title: 'Наші переваги',
        subtitle: 'Чому клієнти обирають нас',
        transparent: 'Прозорі умови',
        transparentDescription: 'Фіксовані ціни без прихованих платежів.',
        check: 'Перевірка авто',
        checkDescription: 'Аналіз історії та стану перед купівлею.',
        support: 'Повний супровід',
        supportDescription: 'Один менеджер на всіх етапах.',
        auctionExperience: 'Досвід аукціонів',
        auctionExperienceDescription: 'Copart, IAAI та інші майданчики.',
        savings: 'Економія бюджету',
        savingsDescription: 'Купівля вигідніше за ринок.',
      },
      howItWorks: {
        title: 'Як це працює',
        subtitle: 'Від вибору авто до отримання в Україні',
        selection: 'Підбір авто',
        selectionDescription:
          'Ви обираєте авто або залишаєте заявку — ми перевіряємо лот.',
        calculation: 'Розрахунок',
        calculationDescription: 'Прорахунок повної вартості авто під ключ.',
        auction: 'Аукціон',
        auctionDescription: 'Участь в аукціоні від вашого імені.',
        delivery: 'Доставка',
        deliveryDescription: 'Логістика, розмитнення та документи.',
        receiving: 'Отримання',
        receivingDescription: 'Готове авто з документами в Україні.',
      },
      search: {
        placeholder: 'Пошук',
        clear: 'Очистити',
      },
      perPage: {
        show: 'Показувати',
        page: 'на сторінці:',
      },
      filters: {
        title: 'Фільтр',
        brand: 'Марка',
        bodyType: 'Тип кузова',
        year: 'Рік випуску',
        price: 'Ціна',
        mileage: 'Пробіг',
        engineType: 'Тип двигуна',
        engineVolume: "Об'єм двигуна(л)",
        batteryCapacity: 'Ємність акумулятора(кВт)',
        seats: 'Кількість місць',
        driveType: 'Тип приводу',
        transmission: 'Тип трансмісії',
        from: 'Від',
        to: 'До',
        invalidRange: 'Від не може бути більшим за до!',
        clear: 'Очистити',
        apply: 'Застосувати',
      },
      auction: {
        breadcrumb: 'Аукціон',
        title: 'Аукціон авто з США',
        photo: 'Фото',
        brandModel: 'Марка / Модель',
        info: 'Інформація',
        condition: 'Стан',
        saleInfo: 'Інформація про продаж',
        bids: 'Ставки',
        showMore: 'Показати більше',
        currentBid: 'Поточна ставка',
        buyNow: 'Купити зараз',
        sold: 'Продано',
        authPrompt: 'Для початку авторизуйтеся',
        soldFor: 'Продано за',
        order: 'Замовити',
        auctionTimeSuffix: 'сек',
      },
      carPage: {
        characteristics: 'Характеристики',
        mileage: 'Пробіг',
        engine: 'Двигун',
        transmission: 'Коробка передач',
        drive: 'Привід',
        seats: 'Кількість місць',
        bodyType: 'Тип кузова',
        color: 'Колір',
        damage: 'Пошкодження',
        secondaryDamage: 'Вторинне пошкодження',
        hasKeys: 'Чи є ключі',
        runsDrive: 'Чи на ходу',
        reset: 'Очистити всі дані (для тестування)',
        price: 'Ціна',
        soldFor: 'Продано за',
        buyNow: 'Купити зараз',
        order: 'Замовити',
        askQuestion: 'Задати питання',
        namePlaceholder: 'Як до вас звертатись?',
        phonePrefix: '+380',
        send: 'Надіслати',
        imageZoom: 'Натисніть на зображення, щоб збільшити',
        expand: 'Розгорнути',
        recommendedCars: 'Рекомендовані авто',
      },
      auth: {
        login: 'Вхід',
        register: 'Реєстрація',
        createAccount: 'Створіть акаунт для участі в аукціоні.',
        signIn: 'Увійдіть у свій акаунт.',
        name: "Ім'я",
        phone: 'Номер телефону',
        password: 'Пароль',
        authError: 'Помилка авторизації',
        serverError: 'Сервер не відповідає',
        submitLogin: 'Увійти',
        submitRegister: 'Зареєструватися',
        loginTab: 'Вхід',
        registerTab: 'Реєстрація',
      },
      admin: {
        panel: 'Адмін панель',
        addCar: 'Додати машину',
        createCar: 'Створити машину',
        listTitle: 'Список машин',
        sortBy: 'Сортувати за',
        name: 'Назва',
        brand: 'Марка',
        model: 'Модель',
        year: 'Рік',
        price: 'Ціна',
        mileage: 'Пробіг',
        auction: 'На аукціон',
        edit: 'Редагувати',
        delete: 'Видалити',
        carNotFound: 'Машину не знайдено',
        editCar: 'Редагувати машину',
        saveChanges: 'Зберегти зміни',
        deleteConfirm: 'Ви точно хочете видалити цю машину?',
        addCarDescription: 'Створіть нову машину для аукціону.',
        adminDescription: 'Додавання, редагування та видалення машин.',
      },
      carForm: {
        title: 'Назва',
        price: 'Ціна',
        isSold: 'Наявність',
        brand: 'Марка',
        model: 'Модель',
        year: 'Рік',
        mileage: 'Пробіг',
        engineType: 'Двигун',
        engineVolume: 'Обсяг двигуна',
        batteryCapacity: 'Ємність батареї',
        transmission: 'Коробка передач',
        driveType: 'Привід',
        seats: 'Сидіння',
        color: 'Колір',
        bodyType: 'Тип кузова',
        isAuction: 'На аукціон',
        damage: 'Пошкодження',
        secondaryDamage: 'Вторинне пошкодження',
        keys: 'Ключі до машини',
        runsDrive: 'На ходу',
        description: 'Опис',
      },
      auctionCard: {
        mileage: 'Пробіг',
        engine: 'Двигун',
        damage: 'Пошкодження',
        secondaryDamage: 'Вторинне пошкодження',
        keys: 'Чи є ключі',
        runsDrive: 'Чи на ходу',
        currentBid: 'Поточна ставка',
        buyNow: 'Купити зараз',
        makeBid: 'Зробити ставку',
        yes: 'Так',
        no: 'Ні',
      },
      carCard: {
        mileage: 'Пробіг',
        engine: 'Двигун',
        transmission: 'Коробка передач',
        drive: 'Привід',
        price: 'Ціна',
        details: 'Детальніше',
        km: 'км',
        kvt: 'кВт',
        l: 'л',
      },
      auctionBot: {
        overbid: 'перебив твою ставку!',
        outbid: 'перебиває ставку!',
      },
      winner: {
        title: 'Вітаємо, ви виграли аукціон!',
        subtitle: 'Ми зв’яжемось з вами найближчим часом.',
      },
      general: {
        loading: 'Завантаження...',
      },
      carValues: {
        engine: {
          benzin: 'Бензин',
          diesel: 'Дизель',
          electric: 'Електро',
          hybrid: 'Гібрид',
        },
        transmission: {
          automatic: 'Автоматична',
          manual: 'Механіка',
        },
        drive: {
          front: 'Передній',
          rear: 'Задній',
          full: 'Повний',
        },
        bodyType: {
          sedan: 'Седан',
          suv: 'Позашляховик',
        },
        color: {
          black: 'Чорний',
          white: 'Білий',
          gray: 'Сірий',
        },
      },
      order: {
        carForOrder: 'Авто на замовлення',
        name: "Ім'я",
        phone: 'Номер телефону',
        details: 'Деталі про авто, яке ви хочете замовити',
      },
      pagination: {
        first: 'Перша',
        previous: 'Попередня',
        next: 'Наступна',
        last: 'Остання',
      },
    },
  },
  en: {
    translation: {
      header: {
        leaveRequest: 'Leave a request',
        adminPanel: 'Admin panel',
        logout: 'Logout',
      },
      sidebar: {
        home: 'Home',
        order: 'Order a car',
        auction: 'Auction',
        delivery: 'Delivery',
        contacts: 'Contacts',
        social: 'Social media',
      },
      footer: {
        branches: 'Our branches',
        company: 'Company',
        services: 'Services',
        socialMedia: 'Follow us',
        location: 'Bila Tserkva',
        address: 'Yaroslav Mudryi St, 45',
        phone1: '+38 (099) 999 99 99',
        phone2: '+38 (066) 666 66 66',
        copy: '© {{year}} Car Auction. All rights reserved.',
      },
      footerLinks: {
        about: 'About us',
        howWeWork: 'How we work',
        delivery: 'Delivery',
        reviews: 'Reviews',
        contacts: 'Contacts',
        usa: 'Cars from USA',
        europe: 'Cars from Europe',
        canada: 'Cars from Canada',
        selection: 'Car selection',
        calculator: 'Calculator',
      },
      hero: {
        titleLine1: 'Find your car on',
        titleHighlight: 'Car Auction',
        subtitle1: 'Selection, inspection, delivery - all in one place.',
        subtitle2:
          'Choose a car from the auction or a custom order, and we will find the best route to your garage.',
        orderButton: 'Order a car',
        auctionButton: 'Go to auction',
        popularCars: 'Popular cars',
      },
      carCards: {
        top: 'Top',
        sales: 'Sales',
      },
      advantages: {
        title: 'Our advantages',
        subtitle: 'Why customers choose us',
        transparent: 'Transparent terms',
        transparentDescription: 'Fixed prices with no hidden fees.',
        check: 'Car inspection',
        checkDescription: 'History and condition analysis before purchase.',
        support: 'Full support',
        supportDescription: 'One manager throughout all stages.',
        auctionExperience: 'Auction experience',
        auctionExperienceDescription: 'Copart, IAAI and other marketplaces.',
        savings: 'Budget savings',
        savingsDescription: 'Buying more profitable than market prices.',
      },
      howItWorks: {
        title: 'How it works',
        subtitle: 'From choosing a car to delivery in Ukraine',
        selection: 'Car selection',
        selectionDescription:
          'You choose a car or leave a request — we verify the lot.',
        calculation: 'Calculation',
        calculationDescription:
          'Calculation of the full cost of the car turnkey.',
        auction: 'Auction',
        auctionDescription: 'Participating in the auction on your behalf.',
        delivery: 'Delivery',
        deliveryDescription: 'Logistics, customs clearance and documents.',
        receiving: 'Receiving',
        receivingDescription: 'Your car with documents in Ukraine.',
      },
      search: {
        placeholder: 'Search',
        clear: 'Clear',
      },
      perPage: {
        show: 'Show',
        page: 'per page:',
      },
      pagination: {
        first: 'First',
        previous: 'Previous',
        next: 'Next',
        last: 'Last',
      },
      filters: {
        title: 'Filter',
        brand: 'Brand',
        bodyType: 'Body type',
        year: 'Year',
        price: 'Price',
        mileage: 'Mileage',
        engineType: 'Engine type',
        engineVolume: 'Engine volume (L)',
        batteryCapacity: 'Battery capacity (kW)',
        seats: 'Seats',
        driveType: 'Drive type',
        transmission: 'Transmission',
        from: 'From',
        to: 'To',
        invalidRange: 'From cannot be greater than To!',
        clear: 'Clear',
        apply: 'Apply',
      },
      auction: {
        breadcrumb: 'Auction',
        title: 'Auction cars from USA',
        photo: 'Photo',
        brandModel: 'Brand / Model',
        info: 'Information',
        condition: 'Condition',
        saleInfo: 'Sale info',
        bids: 'Bids',
        showMore: 'Show more',
        currentBid: 'Current bid',
        buyNow: 'Buy now',
        sold: 'Sold',
        authPrompt: 'Please log in first',
        soldFor: 'Sold for',
        order: 'Order',
        auctionTimeSuffix: 'sec',
        winnerMessage:
          'Congratulations, you won the auction! We will contact you shortly.',
      },
      carPage: {
        characteristics: 'Characteristics',
        mileage: 'Mileage',
        engine: 'Engine',
        transmission: 'Transmission',
        drive: 'Drive',
        seats: 'Seats',
        bodyType: 'Body type',
        color: 'Color',
        damage: 'Damage',
        secondaryDamage: 'Secondary damage',
        hasKeys: 'Has keys',
        runsDrive: 'Runs/Drive',
        reset: 'Clear all data (for testing)',
        price: 'Price',
        soldFor: 'Sold for',
        buyNow: 'Buy now',
        order: 'Order',
        askQuestion: 'Ask a question',
        namePlaceholder: 'How can we address you?',
        phonePrefix: '+380',
        send: 'Send',
        imageZoom: 'Click on the image to enlarge',
        expand: 'Expand',
        recommendedCars: 'Recommended cars',
      },
      auth: {
        login: 'Login',
        register: 'Register',
        createAccount: 'Create an account to participate in the auction.',
        signIn: 'Sign in to your account.',
        name: 'Name',
        phone: 'Phone number',
        password: 'Password',
        authError: 'Authorization error',
        serverError: 'Server does not respond',
        submitLogin: 'Login',
        submitRegister: 'Register',
        loginTab: 'Login',
        registerTab: 'Register',
      },
      admin: {
        panel: 'Admin panel',
        addCar: 'Add car',
        createCar: 'Create car',
        listTitle: 'Car list',
        sortBy: 'Sort by',
        name: 'Name',
        brand: 'Brand',
        model: 'Model',
        year: 'Year',
        price: 'Price',
        mileage: 'Mileage',
        auction: 'On auction',
        edit: 'Edit',
        delete: 'Delete',
        carNotFound: 'Car not found',
        editCar: 'Edit car',
        saveChanges: 'Save changes',
        deleteConfirm: 'Are you sure you want to delete this car?',
        addCarDescription: 'Create a new auction car.',
        adminDescription: 'Adding, editing and deleting cars.',
      },
      carForm: {
        title: 'Title',
        price: 'Price',
        isSold: 'Is sold',
        brand: 'Brand',
        model: 'Model',
        year: 'Year',
        mileage: 'Mileage',
        engineType: 'Engine type',
        engineVolume: 'Engine volume',
        batteryCapacity: 'Battery capacity',
        transmission: 'Transmission',
        driveType: 'Drive type',
        seats: 'Seats',
        color: 'Color',
        bodyType: 'Body type',
        isAuction: 'On auction',
        damage: 'Damage',
        secondaryDamage: 'Secondary damage',
        keys: 'Has keys',
        runsDrive: 'Runs/Drive',
        description: 'Description',
      },
      auctionCard: {
        mileage: 'Mileage',
        engine: 'Engine',
        damage: 'Damage',
        secondaryDamage: 'Secondary damage',
        keys: 'Has keys',
        runsDrive: 'Runs/Drive',
        currentBid: 'Current bid',
        buyNow: 'Buy now',
        makeBid: 'Make a bid',
        yes: 'Yes',
        no: 'No',
      },
      carCard: {
        mileage: 'Mileage',
        engine: 'Engine',
        transmission: 'Transmission',
        drive: 'Drive',
        price: 'Price',
        details: 'Details',
        km: 'km',
        kvt: 'kWt',
        l: 'L',
      },
      auctionBot: {
        overbid: 'overbid your bid!',
        outbid: 'outbids the bid!',
      },
      winner: {
        title: 'Congratulations, you won the auction!',
        subtitle: 'We will contact you shortly.',
      },
      general: {
        loading: 'Loading...',
      },
      carValues: {
        engine: {
          benzin: 'Petrol',
          diesel: 'Diesel',
          electric: 'Electric',
          hybrid: 'Hybrid',
        },
        transmission: {
          automatic: 'Automatic',
          manual: 'Manual',
        },
        drive: {
          front: 'Front-wheel',
          rear: 'Rear-wheel',
          full: 'All-wheel',
        },
        bodyType: {
          sedan: 'Sedan',
          suv: 'SUV',
        },
        color: {
          black: 'Black',
          white: 'White',
          gray: 'Gray',
        },
      },
      order: {
        carForOrder: 'Car for order',
        name: 'Name',
        phone: 'Phone number',
        details: 'Details about the car you want to order',
      },
    },
  },
};

i18n.use(initReactI18next).init({
  resources,
  lng: localStorage.getItem('lang') || 'uk',
  fallbackLng: 'uk',
  interpolation: {
    escapeValue: false,
  },
});

export default i18n;
